In [1]:
import torch
import torch.nn as nn

In [2]:
class Model(nn.Module):
    
    def __init__(self, num_features, hid_dim, Q):
        super().__init__()
        self.layer1 = nn.Linear(num_features, hid_dim, )
        self.layer2 = nn.Linear(hid_dim, Q+1)
        
    def forward(self, x):
        out = torch.tanh(self.layer1(x))
        return torch.tanh(self.layer2(out))

In [3]:
model = Model(784, 128, 5)

In [4]:
bsz = 32
pred = model(torch.randn(32, 784))

In [5]:
pred[0]

tensor([ 0.1538, -0.2699,  0.0631,  0.1370,  0.1525,  0.3346],
       grad_fn=<SelectBackward>)

In [25]:
target = torch.LongTensor(32, 6).random_(2)
target[target == 0] = -1
target[:, -1] = -1

In [27]:
target[0]

tensor([ 1,  1,  1, -1, -1, -1])

In [28]:
(target == 1).size()

torch.Size([32, 6])

In [29]:
pred[0]

tensor([ 0.1538, -0.2699,  0.0631,  0.1370,  0.1525,  0.3346],
       grad_fn=<SelectBackward>)

In [30]:
target[0]

tensor([ 1,  1,  1, -1, -1, -1])

In [40]:
y_len = (target == 1).sum(dim=-1)

In [45]:
pred[target != 1]

tensor([ 0.1370,  0.1525,  0.3346, -0.0214,  0.0395,  0.2207, -0.3111, -0.2524,
        -0.2001,  0.2694, -0.2033,  0.1533, -0.4755, -0.0811,  0.2288, -0.3581,
         0.0348, -0.3792, -0.1841,  0.0346, -0.3769,  0.2206, -0.0462, -0.0744,
        -0.2463, -0.1499,  0.1520,  0.5006,  0.0437,  0.0892,  0.3633, -0.0817,
        -0.1748, -0.1177, -0.0820,  0.0428,  0.2778,  0.0552,  0.0068, -0.6666,
         0.1336, -0.3399,  0.1519, -0.1544, -0.4578, -0.1637, -0.2238, -0.0281,
         0.0509, -0.2604, -0.0480,  0.0253, -0.3028,  0.0163, -0.3523,  0.1998,
         0.3421,  0.2768, -0.1208,  0.0967, -0.1212, -0.1370, -0.1003, -0.1263,
        -0.2182, -0.1465, -0.1741, -0.0500, -0.2250,  0.0793,  0.0221,  0.0800,
        -0.3202,  0.4363, -0.3181,  0.1527,  0.1289, -0.0779, -0.4038, -0.1619,
        -0.1157,  0.0648, -0.2893, -0.2688, -0.0756, -0.0534,  0.2256,  0.1190,
         0.3872,  0.2172, -0.0878,  0.1916, -0.0011, -0.1405, -0.4153,  0.3311,
        -0.6489, -0.0318,  0.2034,  0.12

In [43]:
pred[target == 1]

tensor([ 0.1538, -0.2699,  0.0631, -0.3415, -0.0589,  0.1118, -0.5181,  0.0440,
         0.0274,  0.0588,  0.1181, -0.2815,  0.3124,  0.2901, -0.1496,  0.1104,
         0.1713, -0.1747, -0.5449, -0.5452, -0.6001,  0.2767, -0.0565,  0.0175,
        -0.0140, -0.5178, -0.2032,  0.6539,  0.0596,  0.3487,  0.2369, -0.1497,
         0.0939, -0.0731, -0.0132,  0.1805,  0.0221, -0.2144,  0.3083,  0.0999,
         0.1902,  0.2467,  0.1114,  0.1179,  0.3368,  0.0907, -0.0222, -0.0408,
         0.5809, -0.0505,  0.0016, -0.0960, -0.0569,  0.1871,  0.0078,  0.0211,
         0.0356, -0.3493, -0.1166, -0.1218,  0.0360,  0.5139, -0.2095,  0.2201,
         0.4413, -0.1289,  0.1475, -0.1728,  0.0198, -0.2126,  0.1927,  0.2449,
        -0.1707, -0.1230,  0.4882,  0.2381, -0.0067, -0.2007,  0.0294, -0.1386,
        -0.1191, -0.2374, -0.4394], grad_fn=<IndexBackward>)

In [41]:
y_len

tensor([3, 2, 4, 2, 3, 2, 1, 2, 2, 4, 2, 2, 4, 4, 2, 2, 1, 2, 4, 2, 0, 4, 3, 4,
        3, 2, 2, 3, 4, 1, 3, 4])

tensor([ 0.1538, -0.2699,  0.0631, -0.3415, -0.0589,  0.1118, -0.5181,  0.0440,
         0.0274,  0.0588,  0.1181, -0.2815,  0.3124,  0.2901, -0.1496,  0.1104,
         0.1713, -0.1747, -0.5449, -0.5452, -0.6001,  0.2767, -0.0565,  0.0175,
        -0.0140, -0.5178, -0.2032,  0.6539,  0.0596,  0.3487,  0.2369, -0.1497,
         0.0939, -0.0731, -0.0132,  0.1805,  0.0221, -0.2144,  0.3083,  0.0999,
         0.1902,  0.2467,  0.1114,  0.1179,  0.3368,  0.0907, -0.0222, -0.0408,
         0.5809, -0.0505,  0.0016, -0.0960, -0.0569,  0.1871,  0.0078,  0.0211,
         0.0356, -0.3493, -0.1166, -0.1218,  0.0360,  0.5139, -0.2095,  0.2201,
         0.4413, -0.1289,  0.1475, -0.1728,  0.0198, -0.2126,  0.1927,  0.2449,
        -0.1707, -0.1230,  0.4882,  0.2381, -0.0067, -0.2007,  0.0294, -0.1386,
        -0.1191, -0.2374, -0.4394], grad_fn=<IndexBackward>)

In [ ]:
class BPMLLLoss(nn.Module):

    def __init__(self, size_average=None, reduce=None, reduction='mean'):
        super(_Loss, self).__init__()
        if size_average is not None or reduce is not None:
            self.reduction = _Reduction.legacy_get_string(size_average, reduce)
        else:
            self.reduction = reduction

    def forward(self, input, target):
        # https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/tkde06a.pdf
        # input's shape is (bsz, Q)
        # target's shape is (bsz, Q)
        # target's unique value is in [-1, 1]
        Y = (target == 1)
        Y_bar = (target != 1)
        